# Generated by Django 3.2.11 on 2022-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_estimate', models.IntegerField(blank=True, null=True)),
                ('item_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
