# Generated by Django 3.2.11 on 2022-01-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'wish', 'verbose_name_plural': 'wishes'},
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='item_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='price_estimate',
            new_name='price',
        ),
    ]
