# Generated by Django 3.2.11 on 2022-01-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_rename_ip_address_ip_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='ip_address',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
