# Generated by Django 3.2.11 on 2022-01-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_auto_20220105_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='sess_key',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
